# All application configuration lives in SSM Parameter Store under /miniai/.
# The gateway reads the whole path once at startup (server/config.py).
# Changing a value = terraform apply + restart the gateway. Auditable, versioned,
# and no config drift between what's running and what's in git.

locals {
  config_parameters = {
    "rate-limit-per-min" = var.rate_limit_per_min
    "max-queue-depth"    = var.max_queue_depth
    "queue-timeout-s"    = var.queue_timeout_s
    "require-auth"       = var.require_auth
  }
}

resource "aws_ssm_parameter" "config" {
  for_each = local.config_parameters

  name  = "/miniai/config/${each.key}"
  type  = "String"
  value = tostring(each.value)
}

# The demo token is generated by Terraform and only ever exists in state +
# SSM (SecureString, KMS-encrypted). It never appears in a plist, env file,
# or shell history. Rotate with:
#   terraform apply -replace=random_password.demo_token
resource "random_password" "demo_token" {
  length  = 48
  special = false
}

resource "aws_ssm_parameter" "demo_token" {
  name  = "/miniai/demo-token"
  type  = "SecureString"
  value = random_password.demo_token.result
}
