"""Configuration and secret resolution for miniAI.

ALL runtime configuration lives in AWS SSM Parameter Store under /miniai/,
managed by Terraform (terraform/ssm.tf). The gateway reads the whole
/miniai/config/ path once at startup. Changing a value is a code-reviewed
`terraform apply` + service restart — no config drift, full audit trail.

Resolution order (per key):
  1. SSM Parameter Store            (production source of truth)
  2. MINIAI_* env var               (local dev fallback only, logged)
  3. built-in default               (safe out-of-the-box values)

The demo token is a SecureString at /miniai/demo-token, generated by
Terraform, never present in plists, env files, or shell history.

Bootstrap note, stated honestly: a home Mac mini has no instance role, so a
bootstrap AWS credential must exist on the box (~/.aws), scoped by IAM to
read-only access on /miniai/* and nothing else (terraform/iam.tf). What SSM
buys over plaintext env vars: central rotation, CloudTrail audit of every
read, KMS encryption at rest, and a blast radius of exactly one parameter
path if the host is compromised.
"""

from __future__ import annotations

import logging
import os
from typing import Any

log = logging.getLogger("miniai.config")

AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")
CONFIG_PATH = "/miniai/config/"
TOKEN_PARAM = "/miniai/demo-token"

# key -> (env var fallback, default, type)
SCHEMA: dict[str, tuple[str, Any, type]] = {
    "rate-limit-per-min": ("MINIAI_RATE_LIMIT", 6, int),
    "max-queue-depth": ("MINIAI_MAX_QUEUE", 8, int),
    "queue-timeout-s": ("MINIAI_QUEUE_TIMEOUT", 90, int),
    "require-auth": ("MINIAI_REQUIRE_AUTH", False, bool),
}


def _coerce(raw: str, typ: type) -> Any:
    if typ is bool:
        return raw.strip().lower() in ("true", "1", "yes")
    return typ(raw)


def _ssm_client():
    try:
        import boto3
    except ImportError:
        log.info("boto3 not installed; SSM disabled (dev mode)")
        return None
    return boto3.client("ssm", region_name=AWS_REGION)


def _fetch_ssm_path(path: str) -> dict[str, str] | None:
    """All parameters under a path, e.g. {'rate-limit-per-min': '6', ...}."""
    client = _ssm_client()
    if client is None:
        return None
    try:
        from botocore.exceptions import BotoCoreError, ClientError
        found: dict[str, str] = {}
        paginator = client.get_paginator("get_parameters_by_path")
        for page in paginator.paginate(Path=path, WithDecryption=True):
            for p in page["Parameters"]:
                found[p["Name"].removeprefix(path)] = p["Value"]
        log.info("loaded %d config parameters from SSM %s", len(found), path)
        return found
    except (BotoCoreError, ClientError) as exc:
        log.warning("SSM path read failed for %s: %s", path, type(exc).__name__)
        return None


def _fetch_ssm_param(name: str) -> str | None:
    client = _ssm_client()
    if client is None:
        return None
    try:
        from botocore.exceptions import BotoCoreError, ClientError
        resp = client.get_parameter(Name=name, WithDecryption=True)
        log.info("resolved secret from SSM parameter %s", name)
        return resp["Parameter"]["Value"]
    except (BotoCoreError, ClientError) as exc:
        log.warning("SSM lookup failed for %s: %s", name, type(exc).__name__)
        return None


def load_config() -> dict[str, Any]:
    """Resolve every SCHEMA key: SSM > env > default. Called once at startup."""
    ssm_values = _fetch_ssm_path(CONFIG_PATH) or {}
    config: dict[str, Any] = {}
    for key, (env_var, default, typ) in SCHEMA.items():
        if key in ssm_values:
            config[key] = _coerce(ssm_values[key], typ)
            source = "ssm"
        elif os.environ.get(env_var):
            config[key] = _coerce(os.environ[env_var], typ)
            source = "env (dev fallback)"
        else:
            config[key] = default
            source = "default"
        log.info("config %s=%s [%s]", key, config[key], source)
    return config


def get_demo_token() -> str:
    """Resolve the demo bearer token: SSM > env > empty (public demo mode)."""
    value = _fetch_ssm_param(TOKEN_PARAM)
    if value is not None:
        return value
    env = os.environ.get("MINIAI_TOKEN", "")
    if env:
        log.warning("using MINIAI_TOKEN env var — dev fallback, not for production")
    return env
